# Generated by Django 5.2.10 on 2026-03-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
